export const PORTFOLIO = {
  name: "Kevin Zhu",
  tagline: "Technical Product Manager & weekend photographer",
  location: "Paris, Île-de-France",
  email: "kevzh888@gmail.com",
  headshot: "./uploads/headshot.jpg",

  photoAlbums: [
    {
      id: "travel",
      title: "Travel",
      subtitle: "30 countries · 2023–25",
      gradient: ["#cc2b5e","#753a88"],
      shots: [
        { src: "./uploads/photo1.jpg",    title: "Office, Paris",  place: "Paris, FR",   date: "Oct 2024", camera: "iPhone 15 Pro", lens: "Main",          settings: "1/120 · f/1.78 · ISO 80"  },
        { src: "./uploads/photo2.jpg",    title: "Standup",        place: "Paris, FR",   date: "Oct 2024", camera: "iPhone 15 Pro", lens: "Main",          settings: "1/250 · f/1.78 · ISO 100" },
        { src: "./uploads/DSC03613.jpg",  title: "The Watchman",   place: "Chengdu, CN", date: "Jun 2024", camera: "Sony A7III",    lens: "85mm f/1.4",    settings: "1/200 · f/1.8 · ISO 400" },
        { src: "./uploads/DSC03746.jpg",  title: "Red Qipao",      place: "Chengdu, CN", date: "Jun 2024", camera: "Sony A7III",    lens: "85mm f/1.4",    settings: "1/500 · f/2 · ISO 100"   },
      ],
    },
    {
      id: "paris",
      title: "Paris",
      subtitle: "Home base",
      gradient: ["#ee9ca7","#ffdde1"],
      shots: [
        { src: "./uploads/_DSC8862.jpg",              title: "Haussmann",        place: "Paris, FR",   date: "May 2024", camera: "Sony A7III",    lens: "35mm f/1.8",    settings: "1/500 · f/4 · ISO 100"   },
        { src: "./uploads/_DSC8854.jpg",              title: "Carousel Lights",  place: "Paris, FR",   date: "May 2024", camera: "Sony A7III",    lens: "35mm f/1.8",    settings: "1/125 · f/2 · ISO 400"   },
        { src: "./uploads/DSC04009.jpg",              title: "Monet Umbrella",   place: "Giverny, FR", date: "Jun 2024", camera: "Sony A7III",    lens: "35mm f/1.8",    settings: "1/1000 · f/4 · ISO 100"  },
        { src: "./uploads/DSC03931.jpg",              title: "Glaces Maison",    place: "Île-de-France, FR", date: "Jun 2024", camera: "Sony A7III", lens: "35mm f/1.8", settings: "1/250 · f/4 · ISO 100"   },
        { src: "./uploads/DSC03973-2.jpg",            title: "Red Classic",      place: "Île-de-France, FR", date: "Jun 2024", camera: "Sony A7III", lens: "35mm f/1.8", settings: "1/500 · f/2.8 · ISO 100" },
        { src: "./uploads/DSC04096.jpg",              title: "Gothic Nave",      place: "Île-de-France, FR", date: "Jun 2024", camera: "Sony A7III", lens: "16-35mm f/4", settings: "1/60 · f/4 · ISO 800"   },
        { src: "./uploads/DSC05364.jpg",              title: "Lion Hats",        place: "Paris, FR",   date: "Feb 2024", camera: "Sony A7III",    lens: "85mm f/1.4",    settings: "1/500 · f/1.8 · ISO 400" },
        { src: "./uploads/DSC05525.jpg",              title: "Lunar New Year",   place: "Paris, FR",   date: "Feb 2024", camera: "Sony A7III",    lens: "85mm f/1.4",    settings: "1/400 · f/2 · ISO 800"   },
        { src: "./uploads/DSC05556.jpg",              title: "Portraits",        place: "Paris, FR",   date: "Feb 2024", camera: "Sony A7III",    lens: "85mm f/1.4",    settings: "1/400 · f/1.8 · ISO 800" },
      ],
    },
  ],

  notes: [
    {
      id: "welcome", icon: "🏠", title: "Welcome", date: "Today",
      body: [
        "Hey, welcome to my portfolio 👋",
        "",
        "I'm Kevin — TPM & Cloud/GenAI Engineer based in Paris.",
        "This site is designed like an OS so you can explore it naturally.",
        "",
        "────────────────────────",
        "",
        "What you'll find here",
        "  📸  Photos       — my travel & street photography",
        "  📝  Notes        — résumé, work experience, education",
        "  💳  Wallet       — boarding pass summary",
        "  🎵  Spotify      — lofi tunes while you browse",
        "  👤  Contacts     — how to reach me",
        "  🎱  Magic 8 Ball — ask it anything",
        "",
        "────────────────────────",
        "",
        "Looking for",
        "  IT Strategy Consultant",
        "  Digital Transformation Consultant",
        "  Product Manager / Product Owner",
        "  Project Manager",
        "",
        "  Target: Unicorn · Tech · Consulting",
        "  Available: Sept – Nov 2026",
        "",
        "────────────────────────",
        "",
        "Get in touch",
        "  kevzh888@gmail.com",
      ].join("\n"),
    },
    {
      id: "about", icon: "👋", title: "About me", date: "Today",
      body: "CS Engineer (EPITA – SIGL) & International Project Management graduate (NEOMA). TPM at Equativ, working at the intersection of product, cloud, and Gen AI.\n\nHands-on across consulting, start-ups, and scale-ups — I translate complex technical problems into roadmaps that ship. AWS Certified Solutions Architect. Combine technical depth with strategic product vision.\n\nBased in: Paris, Île-de-France\nRole: Technical Product Manager / Product Owner\nFocus: Cloud architecture, API modernisation, Gen AI integration\nLoves: Photography, ramen, slow Sundays\n\n🔍 Open to opportunities\nLooking for: IT Strategy Consultant · Digital Transformation Consultant · Product Manager/Owner · Project Manager\nEnvironment: Unicorn · Tech company · Consulting\nAvailability: Sept – Nov 2026",
    },
    {
      id: "experience", icon: "💼", title: "Work Experience", date: "May 2026",
      body: [
        "EQUATIV (ex. SmartAdServer) — Paris",
        "[logo:./uploads/logo-equativ.png]",
        "Technical Product Manager / Product Owner",
        "Sept. 2025 – Present",
        "",
        "  · Owned end-to-end delivery across 2 squads (6+ engineers)",
        "  · +75 % performance on core ad-decisioning workflows",
        "  · Eliminated legacy API debt serving 1,500+ clients",
        "  · Redesigned 3 critical workflows (API + UI)",
        "  · Piloted GCP Cloud Storage migration for ad creatives",
        "  Stack: Jira · MySQL · Miro · Confluence · Pendo",
        "",
        "────────────────────────",
        "",
        "ONEPOINT — Paris",
        "[logo:./uploads/logo-onepoint.png]",
        "SI Architecture Consultant (Cloud & Gen AI)",
        "Feb. – Aug. 2025",
        "",
        "  · Serverless RAG on AWS (Bedrock, Lambda, API GW, S3, OpenSearch)",
        "  · Terraform IaC across 4+ client engagements",
        "  · 80 % faster deployments via reusable Terraform modules",
        "  · Gen AI best-practice REX to 25+ consultants",
        "  Stack: AWS · Python · LangChain · Streamlit · Terraform",
        "",
        "────────────────────────",
        "",
        "BPIFRANCE — Paris",
        "[logo:./uploads/logo-bpifrance.png]",
        "Software Engineer",
        "Aug. – Dec. 2024",
        "",
        "  · Built internal mobile mutual-aid app from Figma to prod",
        "  · Refactored backend from Quarkus to Spring Boot",
        "  · Full CI/CD pipeline + Terraform on AWS & GCP",
        "  · Presented to 150+ stakeholders at PI Planning",
        "  Stack: AWS · GCP · Python · Spring Boot · Terraform",
        "",
        "────────────────────────",
        "",
        "MANGER NU! (IoT Startup) — Paris",
        "[logo:./uploads/logo-nu.svg]",
        "Technical Project Manager / Software Engineer",
        "Sept. 2023 – Jan. 2024",
        "",
        "  · Shipped 15+ features on CRM & admin platform",
        "  · Automated CSV reports → 90 % less manual processing",
        "  · Set up sFTP exchange (400+ files)",
        "  Stack: C# · Azure · React · SQL",
      ].join("\n"),
    },
    {
      id: "education", icon: "🎓", title: "Education", date: "2026",
      body: [
        "NEOMA Business School · 2026",
        "  MSc Management de Projet — International Project Management",
        "",
        "EPITA – École Pour l'Informatique et les Techniques Avancées · 2025",
        "  Ingénieur en Informatique — Information Systems & Software Engineering (SIGL)",
      ].join("\n"),
    },
    {
      id: "certs", icon: "🏅", title: "Certifications", date: "2025",
      body: [
        "🟡  AWS Certified Solutions Architect – Associate",
        "     Amazon Web Services · 2025",
        "",
        "🤖  AWS Generative AI Leader",
        "     AWS Skill Builder · 2025",
        "",
        "📋  Professional Scrum Product Owner I (PSPO I)",
        "     Scrum.org · 2025",
        "",
        "🗣️  TOEIC / Cambridge Certificate B2–C1",
        "     ETS Global · 2025",
        "",
        "💎  LVMH Inside Programme",
        "     LVMH · 2025",
      ].join("\n"),
    },
    {
      id: "skills", icon: "🛠️", title: "Skills", date: "2025",
      body: [
        "Programming & Scripting",
        "  Python · C# · C · C++ · Java · JavaScript · TypeScript · Shell/Bash · SQL",
        "",
        "Backend / Full-Stack",
        "  Django (REST API + ORM) · Node.js · .NET · Spring Boot",
        "",
        "Databases & Storage",
        "  PostgreSQL · DynamoDB · MySQL · S3 · EFS",
        "",
        "Cloud & DevOps",
        "  AWS (Lambda · API Gateway · S3 · ECS Fargate · Terraform)",
        "  GCP (Cloud Storage) · Docker · CI/CD (GitHub Actions · Terraform)",
        "",
        "Product & Project",
        "  Jira · Confluence · Agile/Scrum · Kanban · Product KPIs",
        "",
        "Gen AI & Data",
        "  LangChain · Amazon Bedrock · RAG architectures · Streamlit · SQL analytics",
      ].join("\n"),
    },
    {
      id: "hobbies", icon: "🎒", title: "Hobbies", date: "Always",
      body: [
        "📷 Photography — Mostly cityscapes and quiet streets. Keep a journal of every roll.",
        "🍜 Cooking — Multi-year quest for the perfect xiaolongbao. Sourdough is my white whale.",
        "🚲 Cycling — Long Sunday rides along the Seine, pastry stops mandatory.",
        "📖 Reading — Product essays, sci-fi short stories, occasional Murakami.",
        "✈️ Travel — 30 countries and counting — slow trips, cameras heavy, plans loose.",
      ].join("\n"),
    },
    {
      id: "languages", icon: "🌍", title: "Languages", date: "Native",
      body: "FR · French — Native\nZH · Mandarin — Native\nEN · English — B2–C1\nDE · German — B2",
    },
  ],

  links: {
    github: "https://github.com/kevzh888",
    linkedin: "https://www.linkedin.com/in/kevinzhu-kz/",
    portfolio: "https://zjhphotography.myportfolio.com/",
  },
};

// Photography albums mapped for the Photos app (no Contact album)
PORTFOLIO.albums = PORTFOLIO.photoAlbums.map((a) => ({
  id: a.id, title: a.title, subtitle: a.subtitle,
  kind: "photography", cover: a.cover, gradient: a.gradient, shots: a.shots,
}));

// Contact links used by ContactsApp
PORTFOLIO.contactLinks = [
  { label: "Email",     value: "kevzh888@gmail.com",        href: "mailto:kevzh888@gmail.com" },
  { label: "LinkedIn",  value: "linkedin.com/in/kevinzhu-kz", href: PORTFOLIO.links.linkedin },
  { label: "GitHub",    value: "@kevzh888",                 href: PORTFOLIO.links.github },
  { label: "Portfolio", value: "zjhphotography.myportfolio.com", href: PORTFOLIO.links.portfolio },
];
